name: Notion Reminder Every 1.5 Hours

on:
  schedule:
    - cron: '0 9 * * *'     # 10:00 AM BST
    - cron: '30 10 * * *'   # 11:30 AM BST
    - cron: '0 12 * * *'    # 1:00 PM BST
    - cron: '30 13 * * *'   # 2:30 PM BST
    - cron: '0 15 * * *'    # 4:00 PM BST
    - cron: '30 16 * * *'   # 5:30 PM BST
    - cron: '0 18 * * *'    # 7:00 PM BST
    - cron: '30 19 * * *'   # 8:30 PM BST
    - cron: '0 21 * * *'    # 10:00 PM BST
    - cron: '30 22 * * *'   # 11:30 PM BST

  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install notion-client python-dotenv requests

    - name: Run Notion Reminder Bot
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        DATABASE_ID: ${{ secrets.DATABASE_ID }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python notion_reminder_bot.py
